"""added type to users

Revision ID: 00dcd86057fa
Revises: 25ebb8e5338d
Create Date: 2024-11-05 05:54:24.786767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00dcd86057fa'
down_revision: Union[str, None] = '25ebb8e5338d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medpulse_user', sa.Column('user_type', sa.VARCHAR(), server_default='patient', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medpulse_user', 'user_type')
    # ### end Alembic commands ###
