"""added employment type to staff  migration

Revision ID: 0dc8528e1546
Revises: fee7cb056514
Create Date: 2024-12-04 04:28:58.252474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0dc8528e1546'
down_revision: Union[str, None] = 'fee7cb056514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('employment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'employment_type')
    # ### end Alembic commands ###
