"""Page Migration

Revision ID: 1535dcd45700
Revises: 466b2c8883a3
Create Date: 2024-11-14 14:05:43.820197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1535dcd45700'
down_revision: Union[str, None] = '466b2c8883a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('page_content',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paragraph', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['page_uid'], ['page.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('chatparticipant', sa.Column('chat_uid', sa.Uuid(), nullable=False))
    op.add_column('chatparticipant', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.drop_constraint('chatparticipant_chat_id_fkey', 'chatparticipant', type_='foreignkey')
    op.drop_constraint('chatparticipant_user_id_fkey', 'chatparticipant', type_='foreignkey')
    op.create_foreign_key(None, 'chatparticipant', 'medpulse_user', ['user_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chatparticipant', 'chat', ['chat_uid'], ['uid'], ondelete='CASCADE')
    op.drop_column('chatparticipant', 'chat_id')
    op.drop_column('chatparticipant', 'user_id')
    op.add_column('message', sa.Column('sender_uid', sa.Uuid(), nullable=False))
    op.add_column('message', sa.Column('chat_uid', sa.Uuid(), nullable=False))
    op.alter_column('message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'medpulse_user', ['sender_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'chat', ['chat_uid'], ['uid'])
    op.drop_column('message', 'chat_id')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_sender_id_fkey', 'message', 'medpulse_user', ['sender_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['uid'])
    op.alter_column('message', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('message', 'chat_uid')
    op.drop_column('message', 'sender_uid')
    op.add_column('chatparticipant', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chatparticipant', sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chatparticipant', type_='foreignkey')
    op.drop_constraint(None, 'chatparticipant', type_='foreignkey')
    op.create_foreign_key('chatparticipant_user_id_fkey', 'chatparticipant', 'medpulse_user', ['user_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key('chatparticipant_chat_id_fkey', 'chatparticipant', 'chat', ['chat_id'], ['uid'], ondelete='CASCADE')
    op.drop_column('chatparticipant', 'user_uid')
    op.drop_column('chatparticipant', 'chat_uid')
    op.drop_table('page_content')
    op.drop_table('page')
    # ### end Alembic commands ###
