"""Added settings table

Revision ID: 25ebb8e5338d
Revises: f7d7cf4300a2
Create Date: 2024-11-03 15:34:43.389012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25ebb8e5338d'
down_revision: Union[str, None] = 'f7d7cf4300a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('screen_reader', sa.Boolean(), nullable=False),
    sa.Column('on_screen_keyboard', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_reminders', sa.Boolean(), nullable=False),
    sa.Column('sms_reminders', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.Enum('email', 'sms', 'none', name='authtype'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
