"""Initial migration

Revision ID: 9e0ab3c93fd1
Revises: 
Create Date: 2024-11-11 23:02:45.232896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM
from app.db.enums import user_type, auth_type, gender_type, entity_type, action_type

# revision identifiers, used by Alembic.
revision: str = '9e0ab3c93fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
  


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medpulse_user',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_type', sa.Enum('admin', 'patient', 'staff','user', name='user_type'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_type'), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('log',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'get', name='action_type'), nullable=False),
    sa.Column('entity', sa.Enum('user', 'chat', 'admin', 'staff', 'patient', 'page', 'department', 'bill', 'appointment', 'labtest', 'prescription', 'medication', 'allergies', 'diagnosis', name='entity_type'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['medpulse_user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('settings',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('screen_reader', sa.Boolean(), nullable=False),
    sa.Column('on_screen_keyboard', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_reminders', sa.Boolean(), nullable=False),
    sa.Column('sms_reminders', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.Enum('email', 'sms', 'none', name='auth_type'), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['medpulse_user.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('log')
    op.drop_table('medpulse_user')
    # ### end Alembic commands ###

