"""dept,staff,role & permission migration

Revision ID: ccb6d1e6b690
Revises: 1535dcd45700
Create Date: 2024-11-14 19:12:23.595648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccb6d1e6b690'
down_revision: Union[str, None] = '1535dcd45700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_appointment_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('permission',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('role',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rolepermission',
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.Column('permission_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_uid'], ['permission.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_uid'], ['role.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_uid', 'permission_uid')
    )
    op.create_table('staff',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('employment_date', sa.Date(), nullable=False),
    sa.Column('employed_until', sa.Date(), nullable=True),
    sa.Column('role_uid', sa.Uuid(), nullable=False),
    sa.Column('department_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_uid'], ['department.uid'], ),
    sa.ForeignKeyConstraint(['role_uid'], ['role.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['medpulse_user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('rolepermission')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('department')
    # ### end Alembic commands ###
