"""Made dob nullable in medpulse_user

Revision ID: f7d7cf4300a2
Revises: 6cebcbf95de3
Create Date: 2024-10-31 20:50:20.208547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7d7cf4300a2'
down_revision: Union[str, None] = '6cebcbf95de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medpulse_user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medpulse_user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
