"""added attributes for fntend  migration

Revision ID: fee7cb056514
Revises: c64e0c8262c6
Create Date: 2024-12-04 04:17:59.043326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee7cb056514'
down_revision: Union[str, None] = 'c64e0c8262c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('medical_concern', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doctor', sa.Column('assigned_treatment_services', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('medpulse_user', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('medpulse_user', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('medpulse_user', sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('medpulse_user', sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('patient', sa.Column('last_visit', sa.Date(), nullable=True))
    op.drop_column('patient', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('patient', 'last_visit')
    op.drop_column('medpulse_user', 'zip_code')
    op.drop_column('medpulse_user', 'street_address')
    op.drop_column('medpulse_user', 'city')
    op.drop_column('medpulse_user', 'country')
    op.drop_column('doctor', 'assigned_treatment_services')
    op.drop_column('appointment', 'medical_concern')
    # ### end Alembic commands ###
