"""migration with tables

Revision ID: 1c7762a4f6f6
Revises: 0068d8236f53
Create Date: 2024-10-26 17:36:13.160793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7762a4f6f6'
down_revision: Union[str, None] = '0068d8236f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('allergy',
    sa.Column('allergy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('allergy_id')
    )
    op.create_index(op.f('ix_allergy_allergy_id'), 'allergy', ['allergy_id'], unique=False)
    op.create_table('chat',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_chat_id'), 'chat', ['chat_id'], unique=False)
    op.create_table('department',
    sa.Column('dept_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_appointment_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_index(op.f('ix_department_dept_id'), 'department', ['dept_id'], unique=False)
    op.create_table('diagnosis',
    sa.Column('diagnosis_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_diagnosis_diagnosis_id'), 'diagnosis', ['diagnosis_id'], unique=False)
    op.create_table('gender',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender')
    )
    op.create_index(op.f('ix_gender_id'), 'gender', ['id'], unique=False)
    op.create_table('medication',
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('standard_dose', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('active_ingredients', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_index(op.f('ix_medication_medication_id'), 'medication', ['medication_id'], unique=False)
    op.create_table('medplus_user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('settings_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('gender_id', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.settings_id'], name='fk_user_settings_id'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_medplus_user_user_id'), 'medplus_user', ['user_id'], unique=False)
    op.create_table('page',
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_page_page_id'), 'page', ['page_id'], unique=False)
    op.create_table('permission',
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permission_permission_id'), 'permission', ['permission_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('settings',
    sa.Column('settings_id', sa.String(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('screen_reader', sa.Boolean(), nullable=True),
    sa.Column('on_screen_keyboard', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('email_reminders', sa.Boolean(), nullable=True),
    sa.Column('sms_reminders', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.Enum('email', 'sms', 'none', name='authtype'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], name='fk_settings_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settings_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_settings_settings_id'), 'settings', ['settings_id'], unique=False)
    op.create_table('admin',
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=False)
    op.create_table('chat_participant',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.action_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_log_log_id'), 'log', ['log_id'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('message_content', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_message_id'), 'message', ['message_id'], unique=False)
    op.create_table('page_content',
    sa.Column('content_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('paragraph', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_page_content_content_id'), 'page_content', ['content_id'], unique=False)
    op.create_table('patient',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('employment_date', sa.Date(), nullable=False),
    sa.Column('employed_until', sa.Date(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.dept_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['medplus_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=False)
    op.create_table('bill',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status_type', sa.String(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_index(op.f('ix_bill_bill_id'), 'bill', ['bill_id'], unique=False)
    op.create_table('doctor',
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('specializations', sa.String(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('enable_online_appointments', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_index(op.f('ix_doctor_doctor_id'), 'doctor', ['doctor_id'], unique=False)
    op.create_table('insurance',
    sa.Column('insurance_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('policy_no', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insurance_id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_insurance_insurance_id'), 'insurance', ['insurance_id'], unique=False)
    op.create_table('medical_history',
    sa.Column('medical_history_id', sa.String(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodtype'), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medical_history_id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_medical_history_medical_history_id'), 'medical_history', ['medical_history_id'], unique=False)
    op.create_table('appointment',
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatustype'), nullable=False),
    sa.Column('reason_for_visit', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointment_appointment_id'), 'appointment', ['appointment_id'], unique=False)
    op.create_table('lab_test',
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=False),
    sa.Column('date_performed', sa.DateTime(), nullable=True),
    sa.Column('test_status', sa.Enum('PENDING', 'PREFORMED', 'COMPLETED', 'CANCELLED', name='labteststatus'), nullable=False),
    sa.Column('test_kind', sa.Enum('BLOOD_TEST', 'URINE_TEST', 'XRAY', 'MRI', name='labtesttype'), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_lab_test_test_id'), 'lab_test', ['test_id'], unique=False)
    op.create_table('medical_history_allergies',
    sa.Column('medical_history_id', sa.String(), nullable=False),
    sa.Column('allergy_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allergy_id'], ['allergy.allergy_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.medical_history_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medical_history_id', 'allergy_id')
    )
    op.create_table('medical_history_diagnoses',
    sa.Column('medical_history_id', sa.String(), nullable=False),
    sa.Column('diagnosis_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.diagnosis_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.medical_history_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medical_history_id', 'diagnosis_id')
    )
    op.create_table('medical_history_medications',
    sa.Column('medical_history_id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.medical_history_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.medication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medical_history_id', 'medication_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PAYED', 'UNPAYED', 'PENDING', name='paymentstatustype'), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status_type', sa.String(), nullable=True),
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    op.create_table('prescription',
    sa.Column('prescription_id', sa.String(), nullable=False),
    sa.Column('date_prescribed', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'READY', 'NOT_ACTIVE', name='orderstatus'), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_prescription_prescription_id'), 'prescription', ['prescription_id'], unique=False)
    op.create_table('lab_result',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('file_attachment', sa.String(), nullable=True),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test.test_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_lab_result_result_id'), 'lab_result', ['result_id'], unique=False)
    op.create_table('prescribed_medication',
    sa.Column('prescribed_medication_id', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('instruction_details', sa.String(), nullable=True),
    sa.Column('prescription_id', sa.String(), nullable=False),
    sa.Column('medication_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.medication_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.prescription_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescribed_medication_id')
    )
    op.create_index(op.f('ix_prescribed_medication_prescribed_medication_id'), 'prescribed_medication', ['prescribed_medication_id'], unique=False)
    op.create_table('treatment',
    sa.Column('treatment_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('treatment_type', sa.Enum('APPOINTMENT', 'PRESCRIPTION', 'LABTEST', 'OTHER', name='treatmenttype'), nullable=False),
    sa.Column('insured_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'NOT_COVERED', name='insuredstatus'), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('prescription_id', sa.String(), nullable=True),
    sa.Column('labtest_id', sa.String(), nullable=True),
    sa.Column('bill_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.bill_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['labtest_id'], ['lab_test.test_id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.prescription_id'], ),
    sa.PrimaryKeyConstraint('treatment_id')
    )
    op.create_index(op.f('ix_treatment_treatment_id'), 'treatment', ['treatment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_treatment_id'), table_name='treatment')
    op.drop_table('treatment')
    op.drop_index(op.f('ix_prescribed_medication_prescribed_medication_id'), table_name='prescribed_medication')
    op.drop_table('prescribed_medication')
    op.drop_index(op.f('ix_lab_result_result_id'), table_name='lab_result')
    op.drop_table('lab_result')
    op.drop_index(op.f('ix_prescription_prescription_id'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('medical_history_medications')
    op.drop_table('medical_history_diagnoses')
    op.drop_table('medical_history_allergies')
    op.drop_index(op.f('ix_lab_test_test_id'), table_name='lab_test')
    op.drop_table('lab_test')
    op.drop_index(op.f('ix_appointment_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_medical_history_medical_history_id'), table_name='medical_history')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_insurance_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_doctor_doctor_id'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_bill_bill_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_page_content_content_id'), table_name='page_content')
    op.drop_table('page_content')
    op.drop_index(op.f('ix_message_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_log_log_id'), table_name='log')
    op.drop_table('log')
    op.drop_table('chat_participant')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_settings_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_permission_id'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_page_page_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_medplus_user_user_id'), table_name='medplus_user')
    op.drop_table('medplus_user')
    op.drop_index(op.f('ix_medication_medication_id'), table_name='medication')
    op.drop_table('medication')
    op.drop_index(op.f('ix_gender_id'), table_name='gender')
    op.drop_table('gender')
    op.drop_index(op.f('ix_diagnosis_diagnosis_id'), table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index(op.f('ix_department_dept_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_chat_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_allergy_allergy_id'), table_name='allergy')
    op.drop_table('allergy')
    op.drop_table('action')
    # ### end Alembic commands ###
